"""Run the local H-SPDZ-Cloud pipeline over p = 2^127 - 1.

This script regenerates the reproducible local prototype measurements used by
the Wiley revision. It reports controlled single-host and local-process
prototype measurements at the production-strength field configured in
hspdz_cloud_implementation.py, represented with 16-byte field-element encodings.
External-endpoint transport measurements are generated by the TCP/TLS runners.
"""

from __future__ import annotations

import argparse
import csv
import statistics
import sys
import time
import tracemalloc
from pathlib import Path
from typing import Iterable

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from hspdz_cloud_implementation import FIELD_BYTES, P, HSPDZCloud  # noqa: E402


WILEY_DIR = ROOT / "Wiley" / "hspdz_cloud_concurrency_submission"


def write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def mean(rows: Iterable[dict], key: str) -> float:
    return statistics.fmean(float(row[key]) for row in rows)


def stdev(rows: Iterable[dict], key: str) -> float:
    values = [float(row[key]) for row in rows]
    return statistics.stdev(values) if len(values) > 1 else 0.0


def execute_hierarchical(depth: int, n1: int = 5, n2: int = 3, n3: int = 2) -> dict:
    proto = HSPDZCloud([n1, n2, n3])
    x = proto.share_secret(7, 0)
    y = proto.share_secret(3, 0)

    start = time.perf_counter()
    triples = [proto.generate_triple(0) for _ in range(depth)]
    offline_ms = (time.perf_counter() - start) * 1000
    offline_bytes = proto.metrics["communication_bytes"]

    start = time.perf_counter()
    current = x
    for idx in range(depth):
        current = proto.multiply(current, y, triples[idx])
    verify_ok = proto.batch_verify([current], 0)
    edge_online_ms = (time.perf_counter() - start) * 1000
    online_edge_bytes = proto.metrics["communication_bytes"] - offline_bytes

    start_bytes = proto.metrics["communication_bytes"]
    start = time.perf_counter()
    commit = proto.commit_transition(current, 1)
    fog_result, malicious = proto.transition_level(current, 1, commit)
    fog_ms = (time.perf_counter() - start) * 1000
    fog_bytes = proto.metrics["communication_bytes"] - start_bytes

    start_bytes = proto.metrics["communication_bytes"]
    start = time.perf_counter()
    commit2 = proto.commit_transition(fog_result, 2)
    cloud_result, malicious2 = proto.transition_level(fog_result, 2, commit2)
    cloud_ms = (time.perf_counter() - start) * 1000
    cloud_bytes = proto.metrics["communication_bytes"] - start_bytes

    expected = (7 * pow(3, depth, proto.p)) % proto.p
    correct = (
        verify_ok
        and malicious is None
        and malicious2 is None
        and proto.reconstruct(cloud_result) == expected
    )

    total_ms = offline_ms + edge_online_ms + fog_ms + cloud_ms
    return {
        "n1": n1,
        "n2": n2,
        "n3": n3,
        "depth": depth,
        "offline_ms": offline_ms,
        "edge_online_ms": edge_online_ms,
        "fog_transition_ms": fog_ms,
        "cloud_transition_ms": cloud_ms,
        "total_ms": total_ms,
        "offline_bytes": offline_bytes,
        "online_edge_bytes": online_edge_bytes,
        "fog_transition_bytes": fog_bytes,
        "cloud_transition_bytes": cloud_bytes,
        "total_bytes": proto.metrics["communication_bytes"],
        "correct": correct,
    }


def execute_flat(depth: int, n: int = 10) -> dict:
    proto = HSPDZCloud([n])
    x = proto.share_secret(7, 0)
    y = proto.share_secret(3, 0)

    start = time.perf_counter()
    triples = [proto.generate_triple(0) for _ in range(depth)]
    offline_ms = (time.perf_counter() - start) * 1000
    offline_bytes = proto.metrics["communication_bytes"]

    start = time.perf_counter()
    current = x
    for idx in range(depth):
        current = proto.multiply(current, y, triples[idx])
    verify_ok = proto.batch_verify([current], 0)
    online_ms = (time.perf_counter() - start) * 1000
    online_bytes = proto.metrics["communication_bytes"] - offline_bytes

    expected = (7 * pow(3, depth, proto.p)) % proto.p
    return {
        "n": n,
        "depth": depth,
        "offline_ms": offline_ms,
        "online_ms": online_ms,
        "total_ms": offline_ms + online_ms,
        "offline_bytes": offline_bytes,
        "online_bytes": online_bytes,
        "total_bytes": proto.metrics["communication_bytes"],
        "correct": verify_ok and proto.reconstruct(current) == expected,
    }


def measure_fault(n1: int, n2: int = 3, n3: int = 2) -> dict:
    proto = HSPDZCloud([n1, n2, n3])
    shared = proto.share_secret(12345, 0)
    commit = proto.commit_transition(shared, 1)

    tracemalloc.start()
    start = time.perf_counter()
    transitioned, malicious = proto.transition_level(shared, 1, commit, corrupt_parties=[1])
    elapsed_ms = (time.perf_counter() - start) * 1000
    _, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    return {
        "n1": n1,
        "detection_ms": elapsed_ms,
        "peak_memory_mb": peak / (1024 * 1024),
        "detected": transitioned is None and malicious == [1],
    }


def transition_efficiency(n1: int, depth: int, n2: int = 3, n3: int = 2) -> dict:
    row = execute_hierarchical(depth=depth, n1=n1, n2=n2, n3=n3)
    edge_real = row["fog_transition_bytes"]
    fog_real = row["cloud_transition_bytes"]
    edge_ideal = n2 * FIELD_BYTES
    fog_ideal = n3 * FIELD_BYTES
    return {
        "n1": n1,
        "depth": depth,
        "edge_to_fog_eta": edge_ideal / edge_real,
        "fog_to_cloud_eta": fog_ideal / fog_real,
        "edge_to_fog_real_bytes": edge_real,
        "fog_to_cloud_real_bytes": fog_real,
        "edge_to_fog_ideal_bytes": edge_ideal,
        "fog_to_cloud_ideal_bytes": fog_ideal,
    }


def to_signed(value: int, p: int = P) -> int:
    return value - p if value > p // 2 else value


def run_ml_inference(samples: int, n1: int = 5, n2: int = 3, n3: int = 2,
                     scale: int = 1000) -> tuple[list[dict], dict]:
    dataset = load_breast_cancer()
    x_train, x_test, y_train, y_test = train_test_split(
        dataset.data,
        dataset.target,
        test_size=0.30,
        random_state=42,
        stratify=dataset.target,
    )
    scaler = StandardScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled = scaler.transform(x_test)

    model = LogisticRegression(max_iter=2000, solver="lbfgs", random_state=42)
    model.fit(x_train_scaled, y_train)
    plaintext_pred = model.predict(x_test_scaled)
    plaintext_accuracy = accuracy_score(y_test, plaintext_pred)

    weights_fixed = np.rint(model.coef_[0] * scale).astype(object)
    bias_fixed = int(round(float(model.intercept_[0]) * scale * scale))
    x_fixed = np.rint(x_test_scaled * scale).astype(object)

    quantized_scores = [
        int(sum(int(x_fixed[row, col]) * int(weights_fixed[col]) for col in range(x_fixed.shape[1])) + bias_fixed)
        for row in range(x_fixed.shape[0])
    ]
    quantized_pred = np.array([1 if score >= 0 else 0 for score in quantized_scores])
    quantized_accuracy = accuracy_score(y_test, quantized_pred)

    secured_count = min(samples, x_fixed.shape[0])
    rows = []
    start_total = time.perf_counter()
    for sample_idx in range(secured_count):
        proto = HSPDZCloud([n1, n2, n3])
        start = time.perf_counter()
        score = proto.share_secret(bias_fixed, 0)
        for feature_idx, weight in enumerate(weights_fixed):
            feature_share = proto.share_secret(int(x_fixed[sample_idx, feature_idx]), 0)
            score = proto.add(score, proto.multiply_by_constant(feature_share, int(weight)))

        edge_ok = proto.batch_verify([score], 0)
        edge_score = to_signed(proto.reconstruct(score), proto.p)

        commit = proto.commit_transition(score, 1)
        fog_score, fog_malicious = proto.transition_level(score, 1, commit)
        commit2 = proto.commit_transition(fog_score, 2)
        cloud_score, cloud_malicious = proto.transition_level(fog_score, 2, commit2)
        cloud_score_signed = to_signed(proto.reconstruct(cloud_score), proto.p)
        latency_ms = (time.perf_counter() - start) * 1000

        secure_pred = 1 if cloud_score_signed >= 0 else 0
        rows.append({
            "sample": sample_idx,
            "features": x_fixed.shape[1],
            "true_label": int(y_test[sample_idx]),
            "plaintext_pred": int(plaintext_pred[sample_idx]),
            "quantized_pred": int(quantized_pred[sample_idx]),
            "secure_pred": int(secure_pred),
            "quantized_score": int(quantized_scores[sample_idx]),
            "secure_score": int(cloud_score_signed),
            "edge_score": int(edge_score),
            "latency_ms": latency_ms,
            "communication_bytes": proto.metrics["communication_bytes"],
            "edge_mac_ok": bool(edge_ok),
            "fog_malicious": "" if fog_malicious is None else ";".join(map(str, fog_malicious)),
            "cloud_malicious": "" if cloud_malicious is None else ";".join(map(str, cloud_malicious)),
            "score_matches": cloud_score_signed == int(quantized_scores[sample_idx]),
            "prediction_matches_quantized": secure_pred == int(quantized_pred[sample_idx]),
        })

    elapsed_total_ms = (time.perf_counter() - start_total) * 1000
    summary = {
        "dataset": "Wisconsin Diagnostic Breast Cancer",
        "samples_total": int(dataset.data.shape[0]),
        "features": int(dataset.data.shape[1]),
        "train_samples": int(x_train.shape[0]),
        "test_samples": int(x_test.shape[0]),
        "secured_test_samples": secured_count,
        "scale": scale,
        "plaintext_accuracy": float(plaintext_accuracy),
        "quantized_accuracy": float(quantized_accuracy),
        "secured_accuracy": accuracy_score(
            [int(row["true_label"]) for row in rows],
            [int(row["secure_pred"]) for row in rows],
        ) if rows else 0.0,
        "secure_quantized_agreement": sum(1 for row in rows if row["prediction_matches_quantized"]) / secured_count if secured_count else 0.0,
        "score_match_rate": sum(1 for row in rows if row["score_matches"]) / secured_count if secured_count else 0.0,
        "mean_latency_ms": mean(rows, "latency_ms") if rows else 0.0,
        "mean_communication_kb": mean(rows, "communication_bytes") / 1024 if rows else 0.0,
        "total_elapsed_ms": elapsed_total_ms,
    }
    return rows, summary


def plot_outputs(out_dir: Path, latency_rows: list[dict], scalability_rows: list[dict],
                 fault_rows: list[dict], comm_rows: list[dict], comparison_rows: list[dict],
                 eta_rows: list[dict], ml_rows: list[dict]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    def save(fig, name: str) -> None:
        for target in (ROOT / name, WILEY_DIR / name):
            fig.savefig(target, dpi=300, bbox_inches="tight")
        plt.close(fig)

    depths = sorted({int(r["depth"]) for r in latency_rows})
    grouped_latency = {
        depth: [r for r in latency_rows if int(r["depth"]) == depth] for depth in depths
    }
    fig, ax = plt.subplots(figsize=(5.2, 3.4))
    ax.plot(depths, [mean(grouped_latency[d], "offline_ms") + mean(grouped_latency[d], "edge_online_ms") for d in depths], marker="o", label="Edge")
    ax.plot(depths, [mean(grouped_latency[d], "fog_transition_ms") for d in depths], marker="s", label="Fog transition")
    ax.plot(depths, [mean(grouped_latency[d], "cloud_transition_ms") for d in depths], marker="^", label="Cloud transition")
    ax.plot(depths, [mean(grouped_latency[d], "total_ms") for d in depths], marker="D", label="Total")
    ax.set_xlabel("Circuit depth D")
    ax.set_ylabel("Latency (ms)")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.25)
    save(fig, "fig1_latency_per_level.png")

    n_values = sorted({int(r["n1"]) for r in scalability_rows})
    grouped_scalability = {
        n: [r for r in scalability_rows if int(r["n1"]) == n] for n in n_values
    }
    fig, ax = plt.subplots(figsize=(5.2, 3.4))
    ax.errorbar(
        n_values,
        [mean(grouped_scalability[n], "total_ms") for n in n_values],
        yerr=[stdev(grouped_scalability[n], "total_ms") for n in n_values],
        marker="o",
        capsize=3,
    )
    ax.set_xlabel("Number of Edge parties n1")
    ax.set_ylabel("Total latency at D=50 (ms)")
    ax.grid(True, alpha=0.25)
    save(fig, "fig2_scalability.png")

    comm_labels = [r["stage"] for r in comm_rows]
    comm_values = [float(r["bytes"]) / 1024 for r in comm_rows]
    fig, ax = plt.subplots(figsize=(5.2, 3.4))
    ax.bar(comm_labels, comm_values, color=["#4C78A8", "#F58518", "#54A24B"])
    ax.set_ylabel("Communication (KB)")
    ax.tick_params(axis="x", rotation=15)
    save(fig, "fig3_communication_cost.png")

    grouped_fault = {n: [r for r in fault_rows if int(r["n1"]) == n] for n in sorted({int(r["n1"]) for r in fault_rows})}
    fig, ax = plt.subplots(figsize=(5.2, 3.4))
    ax.bar(list(grouped_fault), [mean(grouped_fault[n], "peak_memory_mb") for n in grouped_fault], color="#72B7B2")
    ax.set_xlabel("Number of Edge parties n1")
    ax.set_ylabel("Peak traced memory (MB)")
    save(fig, "fig4_memory_usage.png")

    fig, ax1 = plt.subplots(figsize=(5.2, 3.4))
    ax2 = ax1.twinx()
    n_fault = list(grouped_fault)
    ax1.plot(n_fault, [mean(grouped_fault[n], "detection_ms") for n in n_fault], "o-", color="#4C78A8", label="T_d")
    ax2.plot(n_fault, [mean(grouped_fault[n], "peak_memory_mb") for n in n_fault], "s--", color="#E45756", label="Memory")
    ax1.set_xlabel("Number of Edge parties n1")
    ax1.set_ylabel("Fault detection time (ms)", color="#4C78A8")
    ax2.set_ylabel("Peak memory (MB)", color="#E45756")
    ax1.grid(True, alpha=0.25)
    save(fig, "fig5_fault_detection.png")

    labels = [r["metric"] for r in comparison_rows]
    flat = [float(r["flat"]) for r in comparison_rows]
    hspdz = [float(r["hspdz"]) for r in comparison_rows]
    x = np.arange(len(labels))
    fig, ax = plt.subplots(figsize=(5.8, 3.4))
    ax.bar(x - 0.18, flat, width=0.36, label="Flat baseline")
    ax.bar(x + 0.18, hspdz, width=0.36, label="H-SPDZ-Cloud")
    ax.set_xticks(x, labels, rotation=15, ha="right")
    ax.set_ylabel("Normalized score (lower is better)")
    ax.set_yscale("log")
    ax.legend(fontsize=8)
    save(fig, "fig6_comparison.png")

    grouped_eta = {n: [r for r in eta_rows if int(r["n1"]) == n] for n in sorted({int(r["n1"]) for r in eta_rows})}
    fig, ax = plt.subplots(figsize=(5.2, 3.4))
    ax.plot(
        list(grouped_eta),
        [mean(grouped_eta[n], "edge_to_fog_eta") for n in grouped_eta],
        "o-",
        label="Edge to Fog",
    )
    ax.plot(
        list(grouped_eta),
        [mean(grouped_eta[n], "fog_to_cloud_eta") for n in grouped_eta],
        "s--",
        label="Fog to Cloud",
    )
    ax.set_xlabel("Number of Edge parties n1")
    ax.set_ylabel("Authenticated transition efficiency eta")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.25)
    save(fig, "fig7_transition_efficiency.png")

    if ml_rows:
        fig, ax = plt.subplots(figsize=(5.2, 3.4))
        samples = [int(r["sample"]) for r in ml_rows]
        ax.plot(samples, [float(r["latency_ms"]) for r in ml_rows], "o-", color="#4C78A8")
        ax.set_xlabel("Secured test sample")
        ax.set_ylabel("Secure inference latency (ms)")
        ax.grid(True, alpha=0.25)
        save(fig, "fig8_ml_inference_latency.png")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--runs", type=int, default=5)
    parser.add_argument("--ml-samples", type=int, default=30)
    parser.add_argument("--output-dir", type=Path, default=ROOT / "results" / "local_127bit")
    args = parser.parse_args()

    out_dir = args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    latency_rows = []
    for depth in (10, 25, 50):
        for run in range(args.runs):
            row = execute_hierarchical(depth=depth, n1=5, n2=3, n3=2)
            row["run"] = run
            latency_rows.append(row)
    write_csv(out_dir / "latency_per_level_128bit.csv", latency_rows)

    scalability_rows = []
    for n1 in (3, 5, 7, 9, 10):
        for run in range(args.runs):
            row = execute_hierarchical(depth=50, n1=n1, n2=3, n3=2)
            row["run"] = run
            scalability_rows.append(row)
    write_csv(out_dir / "scalability_128bit.csv", scalability_rows)

    fault_rows = []
    for n1 in (3, 5, 7, 9):
        for run in range(args.runs):
            row = measure_fault(n1=n1, n2=3, n3=2)
            row["run"] = run
            fault_rows.append(row)
    write_csv(out_dir / "fault_detection_128bit.csv", fault_rows)

    comparison_rows_raw = []
    for run in range(args.runs):
        h = execute_hierarchical(depth=50, n1=5, n2=3, n3=2)
        f = execute_flat(depth=50, n=10)
        h["run"] = run
        f["run"] = run
        comparison_rows_raw.append({"run": run, **{f"flat_{k}": v for k, v in f.items()}, **{f"hspdz_{k}": v for k, v in h.items()}})
    write_csv(out_dir / "comparison_flat_vs_hspdz_128bit_raw.csv", comparison_rows_raw)

    flat_online_ms = mean(comparison_rows_raw, "flat_online_ms")
    h_online_ms = mean(comparison_rows_raw, "hspdz_edge_online_ms") + mean(comparison_rows_raw, "hspdz_fog_transition_ms") + mean(comparison_rows_raw, "hspdz_cloud_transition_ms")
    flat_online_bytes = mean(comparison_rows_raw, "flat_online_bytes")
    h_online_bytes = mean(comparison_rows_raw, "hspdz_online_edge_bytes") + mean(comparison_rows_raw, "hspdz_fog_transition_bytes") + mean(comparison_rows_raw, "hspdz_cloud_transition_bytes")
    flat_total_bytes = mean(comparison_rows_raw, "flat_total_bytes")
    h_total_bytes = mean(comparison_rows_raw, "hspdz_total_bytes")
    comparison_rows = [
        {"metric": "Online latency", "flat": 100.0, "hspdz": 100.0 * h_online_ms / flat_online_ms, "unit": "normalized"},
        {"metric": "Online comm.", "flat": 100.0, "hspdz": 100.0 * h_online_bytes / flat_online_bytes, "unit": "normalized"},
        {"metric": "Total comm.", "flat": 100.0, "hspdz": 100.0 * h_total_bytes / flat_total_bytes, "unit": "normalized"},
    ]
    write_csv(out_dir / "comparison_flat_vs_hspdz_128bit.csv", comparison_rows)

    comm_sample = execute_hierarchical(depth=50, n1=5, n2=3, n3=2)
    comm_rows = [
        {"stage": "Offline", "bytes": comm_sample["offline_bytes"]},
        {"stage": "Online Edge", "bytes": comm_sample["online_edge_bytes"]},
        {"stage": "Transitions", "bytes": comm_sample["fog_transition_bytes"] + comm_sample["cloud_transition_bytes"]},
    ]
    write_csv(out_dir / "communication_breakdown_128bit.csv", comm_rows)

    eta_rows = []
    for n1 in (3, 5, 7, 9):
        for depth in (10, 25, 50):
            eta_rows.append(transition_efficiency(n1=n1, depth=depth, n2=3, n3=2))
    write_csv(out_dir / "transition_efficiency_128bit.csv", eta_rows)

    ml_rows, ml_summary = run_ml_inference(samples=args.ml_samples, n1=5, n2=3, n3=2)
    write_csv(out_dir / "ml_inference_breast_cancer_128bit.csv", ml_rows)
    write_csv(out_dir / "ml_inference_breast_cancer_summary.csv", [ml_summary])

    plot_outputs(out_dir, latency_rows, scalability_rows, fault_rows, comm_rows, comparison_rows, eta_rows, ml_rows)

    grouped_latency_50 = [r for r in latency_rows if int(r["depth"]) == 50]
    grouped_fault_5 = [r for r in fault_rows if int(r["n1"]) == 5]
    summary = [
        "# H-SPDZ-Cloud Local Pipeline Summary over p=2^127-1",
        "",
        f"- field prime: `{P}` (`2^127 - 1`)",
        f"- field-element encoding: `{FIELD_BYTES}` bytes",
        f"- runs per repeated configuration: `{args.runs}`",
        "",
        "## Key Results",
        "",
        f"- D=50 total latency mean: `{mean(grouped_latency_50, 'total_ms'):.3f}` ms",
        f"- D=50 communication mean: `{mean(grouped_latency_50, 'total_bytes') / 1024:.3f}` KB",
        f"- n1=5 transition fault-detection mean: `{mean(grouped_fault_5, 'detection_ms'):.3f}` ms",
        f"- online communication reduction vs local flat baseline: `{100 * (1 - h_online_bytes / flat_online_bytes):.2f}%`",
        f"- total communication reduction vs local flat baseline: `{100 * (1 - h_total_bytes / flat_total_bytes):.2f}%`",
        f"- ML dataset: `{ml_summary['dataset']}` ({ml_summary['samples_total']} samples, {ml_summary['features']} features)",
        f"- ML plaintext test accuracy: `{100 * ml_summary['plaintext_accuracy']:.2f}%`",
        f"- ML quantized test accuracy: `{100 * ml_summary['quantized_accuracy']:.2f}%`",
        f"- ML secured inference samples: `{ml_summary['secured_test_samples']}`",
        f"- ML secure accuracy on secured subset: `{100 * ml_summary['secured_accuracy']:.2f}%`",
        f"- ML secure/quantized prediction agreement: `{100 * ml_summary['secure_quantized_agreement']:.2f}%`",
        f"- ML secure/quantized score match rate: `{100 * ml_summary['score_match_rate']:.2f}%`",
        f"- ML mean secure inference latency: `{ml_summary['mean_latency_ms']:.3f}` ms",
        f"- ML mean secure inference communication: `{ml_summary['mean_communication_kb']:.3f}` KB",
        "",
        "## Scope",
        "",
        "These are full local-pipeline measurements over p=2^127-1, represented with 16-byte field-element encodings, for the executable prototype in this repository. The companion three-VPS results cover authenticated multi-region WAN transport validation.",
        "",
    ]
    (out_dir / "summary_128bit.md").write_text("\n".join(summary), encoding="utf-8")
    print("\n".join(summary))


if __name__ == "__main__":
    main()
